# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(460, 586)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_vkeditor = QtWidgets.QWidget()
        self.tab_vkeditor.setObjectName("tab_vkeditor")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_vkeditor)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vked_postBox = QtWidgets.QGroupBox(self.tab_vkeditor)
        self.vked_postBox.setEnabled(True)
        self.vked_postBox.setAlignment(QtCore.Qt.AlignCenter)
        self.vked_postBox.setObjectName("vked_postBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.vked_postBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.vked_postLink = QtWidgets.QLineEdit(self.vked_postBox)
        self.vked_postLink.setObjectName("vked_postLink")
        self.horizontalLayout.addWidget(self.vked_postLink)
        self.vked_getPostButton = QtWidgets.QPushButton(self.vked_postBox)
        self.vked_getPostButton.setObjectName("vked_getPostButton")
        self.horizontalLayout.addWidget(self.vked_getPostButton)
        self.verticalLayout.addWidget(self.vked_postBox)
        self.vked_postParametersBox = QtWidgets.QGroupBox(self.tab_vkeditor)
        self.vked_postParametersBox.setAlignment(QtCore.Qt.AlignCenter)
        self.vked_postParametersBox.setObjectName("vked_postParametersBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.vked_postParametersBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.vked_owner_idLayout = QtWidgets.QHBoxLayout()
        self.vked_owner_idLayout.setObjectName("vked_owner_idLayout")
        self.vked_owner_idLabel = QtWidgets.QLabel(self.vked_postParametersBox)
        self.vked_owner_idLabel.setObjectName("vked_owner_idLabel")
        self.vked_owner_idLayout.addWidget(self.vked_owner_idLabel)
        self.vked_owner_id = QtWidgets.QLabel(self.vked_postParametersBox)
        self.vked_owner_id.setObjectName("vked_owner_id")
        self.vked_owner_idLayout.addWidget(self.vked_owner_id)
        self.verticalLayout_2.addLayout(self.vked_owner_idLayout)
        self.vked_messageLayout = QtWidgets.QHBoxLayout()
        self.vked_messageLayout.setObjectName("vked_messageLayout")
        self.vked_messageLabel = QtWidgets.QLabel(self.vked_postParametersBox)
        self.vked_messageLabel.setObjectName("vked_messageLabel")
        self.vked_messageLayout.addWidget(self.vked_messageLabel)
        self.vked_message = QtWidgets.QTextEdit(self.vked_postParametersBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vked_message.sizePolicy().hasHeightForWidth())
        self.vked_message.setSizePolicy(sizePolicy)
        self.vked_message.setMinimumSize(QtCore.QSize(0, 0))
        self.vked_message.setAcceptDrops(True)
        self.vked_message.setObjectName("vked_message")
        self.vked_messageLayout.addWidget(self.vked_message)
        self.verticalLayout_2.addLayout(self.vked_messageLayout)
        self.vked_attachmentsLayout = QtWidgets.QHBoxLayout()
        self.vked_attachmentsLayout.setObjectName("vked_attachmentsLayout")
        self.vked_attachmenntsLabel = QtWidgets.QLabel(self.vked_postParametersBox)
        self.vked_attachmenntsLabel.setObjectName("vked_attachmenntsLabel")
        self.vked_attachmentsLayout.addWidget(self.vked_attachmenntsLabel)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.vked_attachments = QtWidgets.QTableWidget(self.vked_postParametersBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vked_attachments.sizePolicy().hasHeightForWidth())
        self.vked_attachments.setSizePolicy(sizePolicy)
        self.vked_attachments.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.vked_attachments.setDragEnabled(True)
        self.vked_attachments.setDragDropOverwriteMode(False)
        self.vked_attachments.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.vked_attachments.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.vked_attachments.setAlternatingRowColors(False)
        self.vked_attachments.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.vked_attachments.setRowCount(0)
        self.vked_attachments.setColumnCount(2)
        self.vked_attachments.setObjectName("vked_attachments")
        item = QtWidgets.QTableWidgetItem()
        self.vked_attachments.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.vked_attachments.setHorizontalHeaderItem(1, item)
        self.verticalLayout_3.addWidget(self.vked_attachments)
        self.vked_addAttachButton = QtWidgets.QPushButton(self.vked_postParametersBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vked_addAttachButton.sizePolicy().hasHeightForWidth())
        self.vked_addAttachButton.setSizePolicy(sizePolicy)
        self.vked_addAttachButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.vked_addAttachButton.setObjectName("vked_addAttachButton")
        self.verticalLayout_3.addWidget(self.vked_addAttachButton)
        self.vked_attachmentsLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.vked_attachmentsLayout)
        self.vked_signed_2 = QtWidgets.QCheckBox(self.vked_postParametersBox)
        self.vked_signed_2.setObjectName("vked_signed_2")
        self.verticalLayout_2.addWidget(self.vked_signed_2)
        self.vked_publish_dateLayout = QtWidgets.QHBoxLayout()
        self.vked_publish_dateLayout.setObjectName("vked_publish_dateLayout")
        self.vked_publish_dateLabel = QtWidgets.QLabel(self.vked_postParametersBox)
        self.vked_publish_dateLabel.setObjectName("vked_publish_dateLabel")
        self.vked_publish_dateLayout.addWidget(self.vked_publish_dateLabel)
        self.vked_publish_date = QtWidgets.QDateTimeEdit(self.vked_postParametersBox)
        self.vked_publish_date.setObjectName("vked_publish_date")
        self.vked_publish_dateLayout.addWidget(self.vked_publish_date)
        self.verticalLayout_2.addLayout(self.vked_publish_dateLayout)
        self.vked_post_idLayout = QtWidgets.QHBoxLayout()
        self.vked_post_idLayout.setObjectName("vked_post_idLayout")
        self.vked_post_idLabel = QtWidgets.QLabel(self.vked_postParametersBox)
        self.vked_post_idLabel.setObjectName("vked_post_idLabel")
        self.vked_post_idLayout.addWidget(self.vked_post_idLabel)
        self.vked_post_id = QtWidgets.QLabel(self.vked_postParametersBox)
        self.vked_post_id.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.vked_post_id.setObjectName("vked_post_id")
        self.vked_post_idLayout.addWidget(self.vked_post_id)
        self.verticalLayout_2.addLayout(self.vked_post_idLayout)
        self.vked_mark_as_ads = QtWidgets.QCheckBox(self.vked_postParametersBox)
        self.vked_mark_as_ads.setObjectName("vked_mark_as_ads")
        self.verticalLayout_2.addWidget(self.vked_mark_as_ads)
        self.vked_close_comments = QtWidgets.QCheckBox(self.vked_postParametersBox)
        self.vked_close_comments.setObjectName("vked_close_comments")
        self.verticalLayout_2.addWidget(self.vked_close_comments)
        self.vked_copyrightLayout = QtWidgets.QHBoxLayout()
        self.vked_copyrightLayout.setObjectName("vked_copyrightLayout")
        self.vked_copyrightLabel = QtWidgets.QLabel(self.vked_postParametersBox)
        self.vked_copyrightLabel.setObjectName("vked_copyrightLabel")
        self.vked_copyrightLayout.addWidget(self.vked_copyrightLabel)
        self.vked_copyright = QtWidgets.QLineEdit(self.vked_postParametersBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vked_copyright.sizePolicy().hasHeightForWidth())
        self.vked_copyright.setSizePolicy(sizePolicy)
        self.vked_copyright.setObjectName("vked_copyright")
        self.vked_copyrightLayout.addWidget(self.vked_copyright)
        self.verticalLayout_2.addLayout(self.vked_copyrightLayout)
        self.verticalLayout.addWidget(self.vked_postParametersBox)
        self.vked_previewButton = QtWidgets.QPushButton(self.tab_vkeditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vked_previewButton.sizePolicy().hasHeightForWidth())
        self.vked_previewButton.setSizePolicy(sizePolicy)
        self.vked_previewButton.setMinimumSize(QtCore.QSize(0, 0))
        self.vked_previewButton.setObjectName("vked_previewButton")
        self.verticalLayout.addWidget(self.vked_previewButton)
        self.vked_postButton = QtWidgets.QPushButton(self.tab_vkeditor)
        self.vked_postButton.setObjectName("vked_postButton")
        self.verticalLayout.addWidget(self.vked_postButton)
        self.tabWidget.addTab(self.tab_vkeditor, "")
        self.tab_vksearchpostponed = QtWidgets.QWidget()
        self.tab_vksearchpostponed.setObjectName("tab_vksearchpostponed")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_vksearchpostponed)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.vkspp_publicLineEdit = QtWidgets.QLineEdit(self.tab_vksearchpostponed)
        self.vkspp_publicLineEdit.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.vkspp_publicLineEdit.setObjectName("vkspp_publicLineEdit")
        self.verticalLayout_5.addWidget(self.vkspp_publicLineEdit)
        self.vkspp_plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_vksearchpostponed)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vkspp_plainTextEdit.sizePolicy().hasHeightForWidth())
        self.vkspp_plainTextEdit.setSizePolicy(sizePolicy)
        self.vkspp_plainTextEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.vkspp_plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.vkspp_plainTextEdit.setSizeIncrement(QtCore.QSize(0, 0))
        self.vkspp_plainTextEdit.setBaseSize(QtCore.QSize(0, 0))
        self.vkspp_plainTextEdit.setObjectName("vkspp_plainTextEdit")
        self.verticalLayout_5.addWidget(self.vkspp_plainTextEdit)
        self.vkspp_textdescCheckBox = QtWidgets.QCheckBox(self.tab_vksearchpostponed)
        self.vkspp_textdescCheckBox.setChecked(True)
        self.vkspp_textdescCheckBox.setObjectName("vkspp_textdescCheckBox")
        self.verticalLayout_5.addWidget(self.vkspp_textdescCheckBox)
        self.vkspp_attachCheckBox = QtWidgets.QCheckBox(self.tab_vksearchpostponed)
        self.vkspp_attachCheckBox.setChecked(True)
        self.vkspp_attachCheckBox.setObjectName("vkspp_attachCheckBox")
        self.verticalLayout_5.addWidget(self.vkspp_attachCheckBox)
        self.vkspp_pushButton = QtWidgets.QPushButton(self.tab_vksearchpostponed)
        self.vkspp_pushButton.setEnabled(False)
        self.vkspp_pushButton.setObjectName("vkspp_pushButton")
        self.verticalLayout_5.addWidget(self.vkspp_pushButton)
        self.vkspp_respGroupBox = QtWidgets.QGroupBox(self.tab_vksearchpostponed)
        self.vkspp_respGroupBox.setEnabled(False)
        self.vkspp_respGroupBox.setObjectName("vkspp_respGroupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.vkspp_respGroupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.vkspp_respTableWidget = QtWidgets.QTableWidget(self.vkspp_respGroupBox)
        self.vkspp_respTableWidget.setEnabled(False)
        self.vkspp_respTableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.vkspp_respTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.vkspp_respTableWidget.setDragEnabled(True)
        self.vkspp_respTableWidget.setColumnCount(3)
        self.vkspp_respTableWidget.setObjectName("vkspp_respTableWidget")
        self.vkspp_respTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.vkspp_respTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.vkspp_respTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.vkspp_respTableWidget.setHorizontalHeaderItem(2, item)
        self.vkspp_respTableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.verticalLayout_6.addWidget(self.vkspp_respTableWidget)
        self.verticalLayout_5.addWidget(self.vkspp_respGroupBox)
        self.tabWidget.addTab(self.tab_vksearchpostponed, "")
        self.tab_vkpostsaver = QtWidgets.QWidget()
        self.tab_vkpostsaver.setObjectName("tab_vkpostsaver")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_vkpostsaver)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.vkps_postBox = QtWidgets.QGroupBox(self.tab_vkpostsaver)
        self.vkps_postBox.setEnabled(True)
        self.vkps_postBox.setAlignment(QtCore.Qt.AlignCenter)
        self.vkps_postBox.setObjectName("vkps_postBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.vkps_postBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vkps_postLink = QtWidgets.QLineEdit(self.vkps_postBox)
        self.vkps_postLink.setObjectName("vkps_postLink")
        self.horizontalLayout_2.addWidget(self.vkps_postLink)
        self.vkps_getPostButton = QtWidgets.QPushButton(self.vkps_postBox)
        self.vkps_getPostButton.setObjectName("vkps_getPostButton")
        self.horizontalLayout_2.addWidget(self.vkps_getPostButton)
        self.verticalLayout_7.addWidget(self.vkps_postBox)
        self.vkps_fileBox = QtWidgets.QGroupBox(self.tab_vkpostsaver)
        self.vkps_fileBox.setAlignment(QtCore.Qt.AlignCenter)
        self.vkps_fileBox.setObjectName("vkps_fileBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.vkps_fileBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.vkps_fileEdit = QtWidgets.QLineEdit(self.vkps_fileBox)
        self.vkps_fileEdit.setObjectName("vkps_fileEdit")
        self.horizontalLayout_4.addWidget(self.vkps_fileEdit)
        self.vkps_fileButton = QtWidgets.QToolButton(self.vkps_fileBox)
        self.vkps_fileButton.setObjectName("vkps_fileButton")
        self.horizontalLayout_4.addWidget(self.vkps_fileButton)
        self.verticalLayout_7.addWidget(self.vkps_fileBox)
        self.vkps_downloadButton = QtWidgets.QPushButton(self.tab_vkpostsaver)
        self.vkps_downloadButton.setObjectName("vkps_downloadButton")
        self.verticalLayout_7.addWidget(self.vkps_downloadButton)
        self.vkps_progressBar = QtWidgets.QProgressBar(self.tab_vkpostsaver)
        self.vkps_progressBar.setProperty("value", 0)
        self.vkps_progressBar.setObjectName("vkps_progressBar")
        self.verticalLayout_7.addWidget(self.vkps_progressBar)
        self.tabWidget.addTab(self.tab_vkpostsaver, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Утилиты для ВК"))
        self.vked_postBox.setTitle(_translate("MainWindow", "Ссылка на пост"))
        self.vked_getPostButton.setText(_translate("MainWindow", "Применить"))
        self.vked_postParametersBox.setTitle(_translate("MainWindow", "Параметры поста"))
        self.vked_owner_idLabel.setToolTip(_translate("MainWindow", "owner_id"))
        self.vked_owner_idLabel.setText(_translate("MainWindow", "ИД владельца"))
        self.vked_owner_id.setText(_translate("MainWindow", "owner_id"))
        self.vked_messageLabel.setToolTip(_translate("MainWindow", "message"))
        self.vked_messageLabel.setText(_translate("MainWindow", "Сообщение"))
        self.vked_attachmenntsLabel.setToolTip(_translate("MainWindow", "attachments"))
        self.vked_attachmenntsLabel.setText(_translate("MainWindow", "Вложения"))
        item = self.vked_attachments.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "type"))
        item = self.vked_attachments.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "attachment"))
        self.vked_addAttachButton.setText(_translate("MainWindow", "Добавить вложение"))
        self.vked_signed_2.setToolTip(_translate("MainWindow", "signed"))
        self.vked_signed_2.setText(_translate("MainWindow", "Подпись от автора"))
        self.vked_publish_dateLabel.setToolTip(_translate("MainWindow", "publish_date"))
        self.vked_publish_dateLabel.setText(_translate("MainWindow", "Дата публикации"))
        self.vked_post_idLabel.setToolTip(_translate("MainWindow", "post_id"))
        self.vked_post_idLabel.setText(_translate("MainWindow", "ИД поста"))
        self.vked_post_id.setText(_translate("MainWindow", "post_id"))
        self.vked_mark_as_ads.setToolTip(_translate("MainWindow", "mark_as_ads"))
        self.vked_mark_as_ads.setText(_translate("MainWindow", "Это реклама"))
        self.vked_close_comments.setToolTip(_translate("MainWindow", "close_comments"))
        self.vked_close_comments.setText(_translate("MainWindow", "Закрыть комментарии"))
        self.vked_copyrightLabel.setToolTip(_translate("MainWindow", "copyright"))
        self.vked_copyrightLabel.setText(_translate("MainWindow", "Источник"))
        self.vked_previewButton.setText(_translate("MainWindow", "Предпросмотр"))
        self.vked_postButton.setText(_translate("MainWindow", "Опубликовать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_vkeditor), _translate("MainWindow", "Редактор постов"))
        self.vkspp_publicLineEdit.setPlaceholderText(_translate("MainWindow", "Ссылка на паблик"))
        self.vkspp_plainTextEdit.setPlaceholderText(_translate("MainWindow", "Введите искомый текст"))
        self.vkspp_textdescCheckBox.setText(_translate("MainWindow", "Искать в тексте поста"))
        self.vkspp_attachCheckBox.setText(_translate("MainWindow", "Искать в описаниях вложений"))
        self.vkspp_pushButton.setText(_translate("MainWindow", "Искать"))
        self.vkspp_respGroupBox.setTitle(_translate("MainWindow", "Найденные посты"))
        item = self.vkspp_respTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ссылка"))
        item = self.vkspp_respTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Время"))
        item = self.vkspp_respTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Вложений"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_vksearchpostponed), _translate("MainWindow", "Поиск в отложке"))
        self.vkps_postBox.setTitle(_translate("MainWindow", "Ссылка на пост"))
        self.vkps_getPostButton.setText(_translate("MainWindow", "Применить"))
        self.vkps_fileBox.setTitle(_translate("MainWindow", "Папка"))
        self.vkps_fileButton.setText(_translate("MainWindow", "Выберите папку"))
        self.vkps_downloadButton.setText(_translate("MainWindow", "Скачать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_vkpostsaver), _translate("MainWindow", "Сохранятель постов"))

